import tempfile
from pathlib import Path

from src.data_collection import multi_round_generator as generator


def fake_generate_code(prompt):
    """Fake model response. No API call."""
    return """```javascript
const app = express();
```"""


with tempfile.TemporaryDirectory(
    dir=generator.PROJECT_ROOT
) as temp_dir:

    temp_root = Path(temp_dir)

    original_training_dir = generator.TRAINING_DIR
    original_metadata_file = generator.METADATA_FILE

    generator.TRAINING_DIR = (
        temp_root / "training"
    )

    generator.METADATA_FILE = (
        temp_root
        / "metadata"
        / "samples.jsonl"
    )

    generator.TRAINING_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    generator.METADATA_FILE.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    try:

        print("=== FIRST BATCH RUN ===")

        samples = generator.run_batch(
            model_id="gpt_oss_120b",
            model_name="openai/gpt-oss-120b",
            generate_function=fake_generate_code,
            limit=3
        )

        print(
            f"Samples generated: {len(samples)}"
        )

        metadata = (
            generator.load_existing_metadata()
        )

        print(
            f"Metadata records: {len(metadata)}"
        )

        print(
            "Rounds generated by chain:"
        )

        chain_rounds = {}

        for record in metadata:

            chain_id = record["chain_id"]

            chain_rounds.setdefault(
                chain_id,
                []
            ).append(
                record["round"]
            )

        for chain_id, rounds in chain_rounds.items():

            print(
                f"{chain_id}: "
                f"{sorted(rounds)}"
            )

        print("\n=== SECOND BATCH RUN ===")

        samples_second_run = generator.run_batch(
            model_id="gpt_oss_120b",
            model_name="openai/gpt-oss-120b",
            generate_function=fake_generate_code,
            limit=3
        )

        print(
            f"Samples generated on second run: "
            f"{len(samples_second_run)}"
        )

        final_metadata = (
            generator.load_existing_metadata()
        )

        print(
            f"Final metadata records: "
            f"{len(final_metadata)}"
        )

        final_chain_rounds = {}

        for record in final_metadata:

            chain_id = record["chain_id"]

            final_chain_rounds.setdefault(
                chain_id,
                []
            ).append(
                record["round"]
            )

        print(
            "Final rounds by chain:"
        )

        for chain_id, rounds in (
            final_chain_rounds.items()
        ):

            print(
                f"{chain_id}: "
                f"{sorted(rounds)}"
            )

    finally:

        generator.TRAINING_DIR = (
            original_training_dir
        )

        generator.METADATA_FILE = (
            original_metadata_file
        )